export const FETCH_CLASSES = "FETCH_CLASSES";
export const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_FAILURE = "FETCH_CLASSES_FAILURE";

export const SELECT_CLASS = "SELECT_CLASS";
export const SUBMIT_INFO = "SUBMIT_INFO";

export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
