export const FETCH_CLASSES = "FETCH_CLASSES";
export const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_FAILURE = "FETCH_CLASSES_FAILURE";
export const FETCH_RACES = "FETCH_RACES";
export const FETCH_RACES_SUCCESS = "FETCH_RACES_SUCCESS";
export const FETCH_RACES_FAILURE = "FETCH_RACES_FAILURE";
export const FETCH_SUBCLASSES = "FETCH_SUBCLASSES";
export const FETCH_SUBCLASSES_SUCCESS = "FETCH_SUBCLASSES_SUCCESS";
export const FETCH_SUBCLASSES_FAILURE = "FETCH_SUBCLASSES_FAILURE";

export const SELECT_CLASS = "SELECT_CLASS";
export const SUBMIT_INFO = "SUBMIT_INFO";

export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
